layout: sidebar
style: dark
theme: jekyll-theme-slate
markdown: kramdown

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  facebook: ronak.shah.775
  linkedin: ronakshah94
  # medium: your_username
  twitter: ronakshah94
  
projects:
  - name: FactSet Research Systems
    web_url: https://www.factset.com
    image_url: https://www.banklesstimes.com/wp-content/uploads/2018/02/FactSet-Insight-Round-Logo-2.png

  - name: Bridgewater Associates
    web_url: https://www.bridgewater.com
    image_url: 

  - name: Salesforce
    web_url: https://www.salesforce.com
    image_url: ./assets/salesfore-2.svg